### ISSUE TITLE
update: fixed jparty just had to uninstall it and add it back now the  qr code works

### ISSUE THREAD

**Issue by jordan109** [stuartthomas25/JParty#19]
update may 14 2023 i fixed i uninstall it then put it back now the qr code it works just letting you guys know thanks to Mr. Thomas and ben

**Comment by stuartthomas25** [comment]
JParty is a personal project and comes with no guarantee of support.

I will work on this problem when I get time but I do actually have a real job. If you are motivated, feel free to fix this yourself and submit a pull request.

**Comment by benf2004** [comment]
@jordan109 Could you provide some more details?

**Comment by stuartthomas25** [comment]
You should also make sure the phone and the computer are on the same network and can access local devices.

**Comment by jordan109** [comment]
they are on the same network i think 

> 
yes ben here are more deatils i scan the link open it and it says this site cant be reached it did not do that before the ip link is 192.168.1.1.161:8080 and it will not load no matter which phone i use or type it in it wont work

**Comment by jordan109** [comment]
![2023-05-12](https://github.com/stuartthomas25/JParty/assets/54009552/5f0bfae9-fddc-4b18-85fd-5f7c8e6cdbe1)

**Comment by jordan109** [comment]
never mind i got it to work again i just told me sent a email it works again i uninstalled it then put it back and it worked again so thank you i tryed what you kinda said dlete it then put it back thx
